name: task_currency
description: "Currency Converter App with Clean Architecture"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_form_builder: ^10.2.0
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.2.0
  easy_localization: ^3.0.7

  get_it: ^8.0.3
  injectable: ^2.5.0

  drift: ^2.22.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.28

  dio: ^5.8.0

  extended_image: ^10.0.1

  dartz: ^0.10.1

  fl_chart: ^0.70.2

  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.4.14
  injectable_generator: ^2.7.0
  drift_dev: ^2.22.1

  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
